dream byobu

diff --git a/src/dream_mobile_platform/bin/dream_byobu b/src/dream_mobile_platform/bin/dream_byobu
--- a/src/dream_mobile_platform/bin/dream_byobu
+++ b/src/dream_mobile_platform/bin/dream_byobu
@@ -6,7 +6,7 @@ SESSION_NAME="dream_mobile_base"
 usage(){
     cat << EOF
 This is the main script that builds the workspacem and launches all necessary nodes on Rpi. 
-    - b: build catkin workspace
+    - b: build catkin workspace. If it fails, then the script will exit
     - l : launch all nodes
 EOF
 }
@@ -40,19 +40,23 @@ done
 if [[ $DO_CATKIN_BUILD == true ]]; then
     # WORKDIRECTORY is defined in the dockerfile
     cd ${WORKDIRECTORY} && catkin build && source ${WORKDIRECTORY}/devel/setup.bash
+    if [[ $? -ne 0 ]]; then
+        echo "catkin build failed"
+        exit 1
+    fi
 fi
 
 
-# # Ternary in bash could be tricky. I'm not using that.
-# if [[ $LAUNCH_ALL == true ]]; then 
-#     SEND_KEY="C-m"
-# else
-#     SEND_KEY=""
-# fi
+# Ternary in bash could be tricky. I'm not using that.
+if [[ $LAUNCH_ALL == true ]]; then 
+    SEND_KEY="C-m"
+else
+    SEND_KEY=""
+fi
 
-# byobu new-session -d -s $SESSION_NAME
-# byobu send-keys -t $SESSION_NAME "roslaunch dream_mobile_platform low_level_drivers.launch" ${SEND_KEY}
-# # Rename the window to "drivers".
-# byobu rename-window -t $SESSION_NAME "low_level_drivers"
-# # Attach to the session.
-# byobu attach -t $SESSION_NAME
+byobu new-session -d -s $SESSION_NAME
+byobu send-keys -t $SESSION_NAME "roslaunch dream_mobile_platform low_level_drivers.launch" ${SEND_KEY}
+# Rename the window to "drivers".
+byobu rename-window -t $SESSION_NAME "low_level_drivers"
+# Attach to the session.
+byobu attach -t $SESSION_NAME
